import { useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowLeft, ExternalLink, Github, Menu, Search, X } from "lucide-react";
import source from "@/data/build-your-own-x.md?raw";

type Tutorial = { language: string; title: string; url: string; video: boolean };
type Category = { id: string; title: string; tutorials: Tutorial[] };
const slugify = (value: string) => `build-your-own-${value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
const parseDirectory = (markdown: string): Category[] => {
  const categories: Category[] = []; let current: Category | null = null;
  for (const line of markdown.split("\n")) {
    const heading = line.match(/^#### Build your own `(.+)`/);
    if (heading) { current = { id: slugify(heading[1]), title: heading[1], tutorials: [] }; categories.push(current); continue; }
    if (!current) continue;
    const item = line.match(/^[-*] \[\*\*(.+?)\*\*: _(.+?)_\]\((https?:\/\/[^)]+)\)(.*)$/);
    if (item) current.tutorials.push({ language: item[1], title: item[2], url: item[3], video: item[4].includes("[video]") });
  }
  return categories.filter((category) => category.tutorials.length);
};
const categories = parseDirectory(source);
const languages = Array.from(new Set(categories.flatMap((category) => category.tutorials.map((item) => item.language)))).sort();
const tutorialCount = categories.reduce((total, category) => total + category.tutorials.length, 0);

export default function BuildYourOwn() {
  const [query, setQuery] = useState(""); const [selectedLanguages, setSelectedLanguages] = useState<string[]>([]); const [menuOpen, setMenuOpen] = useState(false);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return categories.map((category) => ({ ...category, tutorials: category.tutorials.filter((item) => (!selectedLanguages.length || selectedLanguages.includes(item.language)) && (!needle || `${category.title} ${item.title} ${item.language}`.toLowerCase().includes(needle))) })).filter((category) => category.tutorials.length); }, [query, selectedLanguages]);
  const toggleLanguage = (language: string) => setSelectedLanguages((selected) => selected.includes(language) ? selected.filter((item) => item !== language) : [...selected, language]);

  return <div className="min-h-screen bg-[#f8f6ef] text-[#151515]">
    <Helmet><title>Build Your Own X — Learn by Recreating Technology | Virelity</title><meta name="description" content="Hundreds of free tutorials for building databases, operating systems, programming languages, games, AI systems, and more from scratch." /></Helmet>
    <header className="sticky top-0 z-40 border-b-2 border-black bg-[#ffbe0b]"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-3 md:px-8"><Link to="/resources" className="flex items-center gap-2 text-sm font-black uppercase tracking-wider"><ArrowLeft className="h-4 w-4" /> Resources</Link><div className="text-center text-xl font-black uppercase tracking-tight sm:text-2xl">Build Your Own X</div><a href="https://github.com/deonmenezes/build-your-own-x" target="_blank" rel="noreferrer" aria-label="View Deon Menezes's Build Your Own X fork on GitHub" className="rounded-full border-2 border-black bg-white p-2 transition-transform hover:-translate-y-0.5"><Github className="h-5 w-5" /></a></div></header>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[280px_minmax(0,1fr)]">
      <aside className={`fixed inset-y-0 left-0 z-50 w-[300px] overflow-y-auto border-r-2 border-black bg-[#151515] p-6 text-white transition-transform lg:sticky lg:top-[62px] lg:z-20 lg:h-[calc(100vh-62px)] lg:w-auto lg:translate-x-0 ${menuOpen ? "translate-x-0" : "-translate-x-full"}`}><div className="mb-6 flex items-center justify-between"><h2 className="text-lg font-black uppercase">Table of contents</h2><button className="lg:hidden" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X /></button></div><nav aria-label="Build categories" className="space-y-1">{categories.map((category) => <a key={category.id} href={`#${category.id}`} onClick={() => setMenuOpen(false)} className="flex justify-between gap-3 rounded px-3 py-2 text-sm font-semibold text-white/75 hover:bg-[#ffbe0b] hover:text-black"><span>{category.title}</span><span className="text-xs opacity-60">{category.tutorials.length}</span></a>)}</nav></aside>
      <main className="min-w-0 px-4 py-8 md:px-8 lg:px-12 lg:py-12">
        <button onClick={() => setMenuOpen(true)} className="mb-5 inline-flex items-center gap-2 border-2 border-black bg-white px-4 py-2 font-bold shadow-[3px_3px_0_#000] lg:hidden"><Menu className="h-4 w-4" /> Categories</button>
        <section className="mb-10 border-2 border-black bg-white p-6 shadow-[7px_7px_0_#000] md:p-10"><p className="mb-3 text-xs font-black uppercase tracking-[0.22em] text-[#c2410c]">Learn by building it yourself</p><h1 className="max-w-4xl text-4xl font-black leading-[0.95] tracking-tight md:text-7xl">What I cannot create, I do not understand.</h1><p className="mt-6 max-w-3xl text-base font-medium text-black/65 md:text-lg">A searchable collection of step-by-step tutorials for recreating the technology you use every day—from databases and operating systems to games, AI, and web browsers.</p><div className="mt-7 flex flex-wrap gap-3 text-sm font-black uppercase"><span className="border-2 border-black bg-[#ffbe0b] px-3 py-2">{categories.length} categories</span><span className="border-2 border-black bg-[#fb5607] px-3 py-2 text-white">{tutorialCount}+ tutorials</span><span className="border-2 border-black bg-[#3a86ff] px-3 py-2 text-white">Free & open</span></div></section>
        <section className="mb-10 space-y-5" aria-label="Directory filters"><label className="relative block"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2" /><span className="sr-only">Search tutorials</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search databases, games, Python..." className="w-full border-2 border-black bg-white py-4 pl-12 pr-4 text-base font-semibold outline-none focus:shadow-[4px_4px_0_#3a86ff]" /></label><div><div className="mb-3 flex items-center justify-between"><h2 className="font-black uppercase">Filter by language</h2>{selectedLanguages.length > 0 && <button onClick={() => setSelectedLanguages([])} className="text-sm font-bold underline">Clear all</button>}</div><div className="flex max-h-40 flex-wrap gap-2 overflow-y-auto pr-2">{languages.map((language) => <button key={language} onClick={() => toggleLanguage(language)} aria-pressed={selectedLanguages.includes(language)} className={`border-2 border-black px-3 py-1.5 text-xs font-black transition-transform hover:-translate-y-0.5 ${selectedLanguages.includes(language) ? "bg-black text-white" : "bg-white"}`}>{language}</button>)}</div></div></section>
        <div className="space-y-12">{filtered.map((category, categoryIndex) => <section id={category.id} key={category.id} className="scroll-mt-24"><div className="mb-5 flex items-end gap-4 border-b-2 border-black pb-3"><span className="text-sm font-black text-[#fb5607]">{String(categoryIndex + 1).padStart(2, "0")}</span><h2 className="text-3xl font-black tracking-tight md:text-4xl">{category.title}</h2><span className="mb-1 text-sm font-bold text-black/45">{category.tutorials.length}</span></div><div className="grid gap-3 xl:grid-cols-2">{category.tutorials.map((tutorial) => <a key={`${tutorial.url}-${tutorial.title}`} href={tutorial.url} target="_blank" rel="noreferrer" className="group flex min-h-28 flex-col justify-between border-2 border-black bg-white p-4 transition-all hover:-translate-y-1 hover:bg-[#fff4c7] hover:shadow-[5px_5px_0_#000]"><div className="flex items-start justify-between gap-4"><h3 className="font-bold leading-snug">{tutorial.title}</h3><ExternalLink className="h-4 w-4 shrink-0 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></div><div className="mt-4 flex items-center gap-2"><span className="border border-black bg-[#ffbe0b] px-2 py-1 text-[11px] font-black uppercase">{tutorial.language}</span>{tutorial.video && <span className="text-[11px] font-black uppercase text-[#fb5607]">Video</span>}</div></a>)}</div></section>)}{!filtered.length && <div className="border-2 border-black bg-white p-10 text-center shadow-[6px_6px_0_#000]"><h2 className="text-2xl font-black">No tutorials found</h2><p className="mt-2 text-black/60">Try a different search or clear your language filters.</p></div>}</div>
        <footer className="mt-16 border-t-2 border-black py-8 text-sm font-semibold text-black/60">Virelity adaptation by Deon Menezes. View <a className="font-black text-black underline" href="https://github.com/deonmenezes/build-your-own-x" target="_blank" rel="noreferrer">Deon's fork</a> or the CC0-licensed <a className="font-black text-black underline" href="https://github.com/codecrafters-io/build-your-own-x" target="_blank" rel="noreferrer">original upstream project</a>.</footer>
      </main>
    </div>{menuOpen && <button aria-label="Close category menu" onClick={() => setMenuOpen(false)} className="fixed inset-0 z-40 bg-black/50 lg:hidden" />}
  </div>;
}
