import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Bot, ExternalLink, Github, GraduationCap, Scale, ShieldCheck, Sparkles, Target } from "lucide-react";

type Resource = { name: string; description: string; href: string; label: string; icon: typeof ShieldCheck; featured?: boolean };

const aiTools: Resource[] = [
  { name: "Codex Security", description: "OpenAI's application-security agent builds a threat model, validates findings in an isolated environment, and proposes patches for human review.", href: "https://openai.com/index/codex-security-now-in-research-preview/", label: "Official OpenAI", icon: Sparkles, featured: true },
  { name: "Strix", description: "An open-source agentic security platform designed to identify and validate exploitable vulnerabilities in modern applications.", href: "https://github.com/usestrix/strix", label: "Open-source", icon: Bot, featured: true },
  { name: "Shannon", description: "An open-source white-box AI pentester that combines source analysis with dynamic validation for web applications and APIs you are authorized to test.", href: "https://github.com/KeygraphHQ/shannon", label: "White-box pentesting", icon: Bot, featured: true },
  { name: "CAI", description: "A modular open-source framework for building offensive and defensive cybersecurity agents with multi-model and security-tool integrations.", href: "https://github.com/aliasrobotics/CAI", label: "Agent framework", icon: Bot },
  { name: "PentestGPT", description: "A Docker-first agentic framework for structured penetration-testing workflows, CTFs, session persistence, and reproducible lab environments.", href: "https://github.com/GreyDGL/PentestGPT", label: "Research framework", icon: Target },
  { name: "Raptor", description: "An AI security-agent framework that combines adversarial workflows, specialist agents, Semgrep packs, and structured SARIF output.", href: "https://github.com/gadievron/raptor", label: "GitHub repository", icon: Github },
  { name: "MantisHack", description: "Deon's autonomous security-research framework for controlled, evidence-driven vulnerability hunting and verification.", href: "https://github.com/deonmenezes/mantishack", label: "Deon's repository", icon: Target, featured: true },
  { name: "GitHub Security Lab Taskflow Agent", description: "GitHub Security Lab's experimental MCP-enabled, YAML-driven multi-agent framework for collaborative security-research workflows.", href: "https://github.com/GitHubSecurityLab/seclab-taskflow-agent", label: "Official GitHub", icon: Github },
  { name: "Snyk Agent Scan", description: "Scans local AI-agent components, MCP servers, and skills for prompt injection, tool poisoning, hidden payloads, and risky data handling.", href: "https://github.com/snyk/agent-scan", label: "Agent supply chain", icon: ShieldCheck },
  { name: "Cisco AI Defense Scanners", description: "An official collection covering agent skills, MCP servers, A2A communication, AI bills of materials, model files, and RAG infrastructure.", href: "https://cisco-ai-defense.github.io/", label: "Defensive toolkit", icon: ShieldCheck },
  { name: "GitHub CodeQL", description: "Query code like data to find vulnerability patterns, audit repositories, and automate security checks in GitHub Actions.", href: "https://codeql.github.com/", label: "Static analysis", icon: Github },
  { name: "Semgrep", description: "Fast, customizable static analysis for detecting insecure code patterns and enforcing secure coding rules.", href: "https://semgrep.dev/docs/", label: "Developer tool", icon: ShieldCheck },
];

const learnAndPractice: Resource[] = [
  { name: "PortSwigger Web Security Academy", description: "Free, interactive labs covering SQL injection, XSS, access control, SSRF, API testing, Web LLM attacks, and more.", href: "https://portswigger.net/web-security", label: "Start here", icon: GraduationCap, featured: true },
  { name: "OWASP Web Security Testing Guide", description: "A comprehensive, community-maintained framework for testing web applications and services.", href: "https://owasp.org/www-project-web-security-testing-guide/latest/", label: "Testing methodology", icon: GraduationCap },
  { name: "OWASP Top 10", description: "Learn the most critical web-application security risks and the controls used to prevent them.", href: "https://owasp.org/www-project-top-ten/", label: "Foundations", icon: ShieldCheck },
  { name: "HackerOne Hacktivity", description: "Study responsibly disclosed vulnerability reports and learn how experienced researchers explain impact and remediation.", href: "https://hackerone.com/hacktivity", label: "Real reports", icon: Target },
  { name: "Hacker101", description: "Free lessons and capture-the-flag challenges created to teach practical web-security and bug-bounty skills.", href: "https://www.hacker101.com/", label: "Free course", icon: GraduationCap },
  { name: "GitHub Security Lab", description: "Security research, CodeQL learning materials, vulnerability write-ups, and open-source security projects.", href: "https://securitylab.github.com/", label: "Research", icon: Github },
];

const bountyPlatforms: Resource[] = [
  { name: "HackerOne", description: "Find public vulnerability-disclosure and bug-bounty programs with clearly defined scope and rules.", href: "https://hackerone.com/directory/programs", label: "Programs", icon: Target },
  { name: "Bugcrowd", description: "Browse authorized programs and read each target's scope, testing rules, and reward structure before starting.", href: "https://bugcrowd.com/engagements", label: "Programs", icon: Target },
  { name: "Intigriti", description: "A responsible-disclosure and bug-bounty platform with public programs, learning content, and researcher resources.", href: "https://www.intigriti.com/researchers/bug-bounty-programs", label: "Programs", icon: Target },
  { name: "disclose.io", description: "A legal and policy resource for safe-harbor language and good-faith vulnerability disclosure.", href: "https://disclose.io/", label: "Safe harbor", icon: Scale },
];

const videoScript = `ChatGPT—available to almost anyone—helped expose a zero-day during an unprecedented security incident involving Hugging Face, a platform that hosts millions of AI models.

That matters because AI is making it dramatically easier to find security weaknesses. In the wrong hands, a single vulnerability can cause enormous damage. But when researchers work legally and disclose issues responsibly, those same skills can protect millions of people—and qualifying reports may earn serious bug-bounty rewards.

So I gathered the best resources to help you learn: Codex Security, Strix, Raptor, MantisHack, PortSwigger's free labs, OWASP's testing guide, and the platforms where companies publish authorized targets.

Only test systems you own or have explicit permission to test. Stay inside the program's scope, document everything, and disclose responsibly.

Comment “SECURITY” and follow me, and I'll send the full resource list to your DMs.`;

function ResourceGrid({ resources }: { resources: Resource[] }) {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{resources.map((resource) => { const Icon = resource.icon; return <a key={resource.name} href={resource.href} target="_blank" rel="noreferrer" className={`group flex min-h-64 flex-col justify-between rounded-2xl border p-6 transition-all hover:-translate-y-1 hover:shadow-xl ${resource.featured ? "border-primary/60 bg-primary/10" : "border-border bg-card"}`}><div><div className="mb-8 flex items-start justify-between"><span className="rounded-xl border border-border bg-background p-3"><Icon className="h-6 w-6 text-primary" /></span><ExternalLink className="h-5 w-5 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div><span className="text-xs font-bold uppercase tracking-[0.16em] text-primary">{resource.label}</span><h3 className="mt-2 text-2xl font-bold">{resource.name}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{resource.description}</p></div><span className="mt-6 inline-flex items-center gap-2 font-bold text-primary">Open resource <ArrowRight className="h-4 w-4" /></span></a>; })}</div>;
}

export default function SecurityResources() {
  return <div className="min-h-screen bg-background text-foreground">
    <Helmet><title>Best AI Security Harnesses & Bug Bounty Resources | Virelity</title><meta name="description" content="Explore Strix, MantisHack, Shannon, CAI, PentestGPT, Raptor, defensive scanners, hands-on labs, and responsible vulnerability disclosure resources." /><link rel="canonical" href="https://www.virelity.com/security-resources" /></Helmet>
    <header className="sticky top-0 z-40 border-b border-border bg-background/90 backdrop-blur-xl"><div className="container mx-auto flex h-16 items-center justify-between px-4"><Link to="/resources" className="inline-flex items-center gap-2 font-semibold"><ArrowLeft className="h-4 w-4" /> Resources</Link><span className="text-sm font-black uppercase tracking-[0.16em] text-primary">Security Field Guide</span><a href="#toolkit" className="rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Explore tools</a></div></header>
    <main>
      <section className="relative overflow-hidden border-b border-border"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,hsl(var(--primary)/.18),transparent_35%)]" /><div className="container relative mx-auto grid gap-10 px-4 py-20 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-28"><div><span className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-primary"><ShieldCheck className="h-4 w-4" /> Authorized research only</span><h1 className="mt-7 text-5xl font-black leading-[.95] tracking-tight md:text-7xl">AI changed how vulnerabilities are found.</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-foreground md:text-xl">Learn how defenders use AI-assisted security tools, practice safely in purpose-built labs, and report real issues through programs that explicitly authorize research.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#toolkit" className="inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3 font-bold text-primary-foreground">Open the toolkit <ArrowRight className="h-5 w-5" /></a><a href="#roadmap" className="rounded-xl border border-border bg-card px-6 py-3 font-bold">See the roadmap</a></div></div><div className="rounded-3xl border border-primary/40 bg-card p-7 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">The incident behind this guide</p><h2 className="mt-4 text-3xl font-bold">A model found and exploited a zero-day during an evaluation.</h2><p className="mt-4 leading-relaxed text-muted-foreground">OpenAI reported that its models chained vulnerabilities across a research environment and Hugging Face infrastructure, including a responsibly disclosed zero-day. It is a powerful warning—and a reason defensive security skills matter more than ever.</p><a href="https://openai.com/index/hugging-face-model-evaluation-security-incident/" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 font-bold text-primary">Read OpenAI's disclosure <ExternalLink className="h-4 w-4" /></a></div></div></section>

      <section id="roadmap" className="container mx-auto px-4 py-20"><div className="max-w-3xl"><span className="text-xs font-bold uppercase tracking-[0.18em] text-primary">A responsible path</span><h2 className="mt-3 text-4xl font-black md:text-5xl">Learn. Practice. Hunt. Disclose.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["01","Learn the foundations","Study HTTP, authentication, access control, common vulnerability classes, and secure coding."],["02","Practice in labs","Use intentionally vulnerable applications and CTFs—never random websites."],["03","Choose a program","Read the scope, exclusions, rate limits, and safe-harbor terms before touching a target."],["04","Report clearly","Provide reproducible steps, evidence, impact, and remediation without exposing user data."]].map(([number,title,body]) => <div key={number} className="rounded-2xl border border-border bg-card p-6"><span className="text-4xl font-black text-primary/35">{number}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-muted-foreground">{body}</p></div>)}</div></section>

      <section id="toolkit" className="container mx-auto px-4 pb-20"><div className="mb-9"><span className="text-xs font-bold uppercase tracking-[0.18em] text-primary">AI-assisted security</span><h2 className="mt-3 text-4xl font-black md:text-5xl">Security harnesses worth knowing</h2><p className="mt-4 max-w-3xl text-muted-foreground">A curated mix of autonomous testing harnesses, research frameworks, source-code analysis, and defensive agent-supply-chain scanners. Use offensive tools only on your own code, isolated labs, or targets that explicitly authorize testing.</p></div><ResourceGrid resources={aiTools} /></section>
      <section className="border-y border-border bg-secondary/30"><div className="container mx-auto px-4 py-20"><div className="mb-9"><span className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Build real skill</span><h2 className="mt-3 text-4xl font-black md:text-5xl">Learn and practice safely</h2></div><ResourceGrid resources={learnAndPractice} /></div></section>
      <section className="container mx-auto px-4 py-20"><div className="mb-9"><span className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Authorized targets</span><h2 className="mt-3 text-4xl font-black md:text-5xl">Find programs and disclose responsibly</h2></div><ResourceGrid resources={bountyPlatforms} /></section>

      <section className="container mx-auto px-4 pb-24"><div className="overflow-hidden rounded-3xl border border-primary/50 bg-card"><div className="border-b border-border bg-primary/10 p-6 md:p-8"><span className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Your original video script</span><h2 className="mt-3 text-3xl font-black md:text-4xl">Security resources CTA</h2></div><div className="whitespace-pre-line p-6 text-lg leading-relaxed text-muted-foreground md:p-8">{videoScript}</div></div></section>
      <section className="border-t border-border bg-[#0b0d10] text-white"><div className="container mx-auto px-4 py-12"><div className="flex items-start gap-4"><Scale className="mt-1 h-7 w-7 shrink-0 text-primary" /><div><h2 className="text-2xl font-bold">Permission is the line.</h2><p className="mt-2 max-w-4xl text-white/65">Do not scan, probe, exploit, access, or retain data from systems unless you own them or have explicit authorization. Bug-bounty rewards are never guaranteed. Follow each program's scope, stop conditions, data-handling rules, and disclosure process.</p></div></div></div></section>
    </main>
  </div>;
}
